# Generated by Django 4.2.2 on 2024-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Head0', models.CharField(default='', max_length=50)),
                ('Head1', models.CharField(default='', max_length=50)),
                ('Head2', models.CharField(default='', max_length=50)),
                ('pub_Date', models.DateField()),
                ('Thumbnail', models.ImageField(default='', upload_to='Shop/images')),
            ],
        ),
    ]
